### PR TITLE
Use create-react-app to create a basic React app.

### PR DESCRIPTION
**Pull request by adamaverycole**
Completing all of the following:
1. Use create-react-app to create a basic React app.
2. Add YouVersion's Melos component library as a dependency for this project.
3. Create one or two example routes, so others can see a template of how to add a new route to show their component or page.
4. Create a basic menu / "table of contents" on the home page, of links that navigate to each page/route.
5. Commit this basic app as the foundational boilerplate that others will contribute their solutions onto.

### CODE REVIEW

**Comment by tcg** [comment]
@adamaverycole Thanks so much for getting this started! I saw your comment on #1 and "basic" is perfect for this project so far!

I realized I left something out when I wrote up the description for this, and I'm sorry... Do you mind moving the `Topic[s]` Components into a `components` subdirectory, and import them from there? 

That will be a better example of what others should do in the future, when they add custom components, and sets things up for the future.

**Comment by adamaverycole** [comment]
@tcg Not a problem! I'll make those changes and let you know when it's ready.

**Comment by adamaverycole** [comment]
@tcg What is your policy for codeclimate errors? There are ~580 different errors for this last commit that I made. Some seem trivial but I want to honor whatever standards you have in place.

**Comment by michael-martin-al** [comment]
@adamaverycole don't worry about CodeClimate for now. I just started setting it up today, but I haven't laid down the official set of rules yet. Sorry to trip up your PR.

**Comment by adamaverycole** [comment]
Perfect! I think my PR is ready to be reviewed again. I got those components refactored and moved into their own folders.

**Comment by tcg** [comment]
👍🏽

Looks great to me! 

@adamaverycole  Thanks SO MUCH for jumping in and getting this off the ground!

**Comment by tcg** [comment]
closes #1

**Pull request merged**
