### PR TITLE
Updates npm/yarn dependencies

### LINKED ISSUE #33: Github Security Alerts (falling behind a bit)
For admins, Github is displaying the following list of known issues with dependencies of this project. Since this is client-side only, and a "work in progress" project for React components, these aren't *critical* at the moment. That said, it would be nice if things didn't fall too far behind before development ramps up again this year. 

The `yarn audit` list is also *really* long 😬 😬 😬 

Currently, it *might* just be a matter of updating a couple of the base dependencies in our `package.json` file, and making sure things still behave the same afterward. Noting / filing a new issue if something is broken after upgrading dependencies. 

Assumed steps: 

- Get a fresh clone
- Make sure `yarn` is up to date
- Run `yarn` to install dependencies 
- Run `yarn start` and poke around to see how things work currently 
- Review the github list, or `yarn audit`, and update necessary base dependencies
- Run `yarn start` again and check that things behave the same as before 
- - If not, file a new issue that "upgrading dependencies breaks [thing/behavior]" with as much specific detail as might be related (specific dependency updated, specific before/after behavior if possible, etc) 

image

### PR DESCRIPTION
**Pull request by damcclean**
Fixes #33

### CODE REVIEW

**Comment by tcg** [comment]
@damcclean Ah, I realized we don't have automatic review builds turned on over here! (I'm spoiled).

Assuming you checked this out and things appear to work as before? 

Also, I guess we have some npm+yarn confusion happening. Did you just sync/lock both lockfiles with the latest versions?

**Comment by damcclean** [comment]
I just went ahead and did a `npm update`. Was that fine? I tried to do a `yarn audit` like you said in the issue but the command didn't work/exist.

**Comment by tcg** [comment]
Ah, sounds like maybe you're on an older version of yarn. If I run `yarn --version` I get 
`1.12.3`. I'm not sure exactly when they introduced `audit`. There's also an `npm audit` that does (at least essentially) the same thing. I'm looking through the list and I'm not sure many of the notices are things we have control over. 

I'll do a comparison to confirm, and post back in a while, but this PR might be good to go. 

Thanks!

**Comment by tcg** [comment]
@michael-martin-al  If you can provide some input to clarify something that's not making sense to me: 

If I do the following: (Assuming `npm`, but same is true w/ Yarn)

- Checkout this branch 
- rm node_modules
- run npm install (and/or npm update, etc) 

I see the following still (post install, and from : 

```
added 356 packages from 207 contributors, removed 232 packages, updated 330 packages and audited 22217 packages in 31.422s
found 127 vulnerabilities (72 low, 35 moderate, 19 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

Also, versions seem to get bumped in the package.json (which I think npm does to match your most recent version w/ semver ranges just to keep things "fresh"). 

*However*, if I... 

- Checkout this branch 
- rm node_modules
- *also rm relevant lock files*, e.g., `package-lock.json` or `yarn.lock`
- run npm install

I see the following post install/audit: 

```
audited 19115 packages in 14.023s
found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
```

With the only *other* difference being some warnings about missing peer dependencies. 

My conclusions: 

Maybe peer deps are in the lock files?  BUT, the app appears to work just fine, so...? 🤷🏽‍♂️

Might I be truly overlooking something important, or perhaps do the lockfiles have some cruft in them maybe?

**Pull request closed without merging**
